version: '3'

services:
  k-k-pro:
    image: dr.k-k.pro/k-k.pro
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
  blog-k-k-pro:
    image: dr.k-k.pro/blog.k-k.pro
    restart: unless-stopped
    ports:
      - 127.0.0.1:3040:3000
  o-k-pro:
    image: dr.k-k.pro/o-k.pro
    restart: unless-stopped
    ports:
      - 127.0.0.1:3010:3000
