version: '3'

services:
  k-k-io:
    image: dr.k-k.io/k-k.io
    restart: unless-stopped
    ports:
      - 3000:3000
  olga-k-k-io:
    image: dr.k-k.io/olga.k-k.io
    restart: unless-stopped
    ports:
      - 3010:3000
