version: '3'

services:
  guessir-web:
    image: dr.k-k.io/guessir-web
    restart: unless-stopped
    ports:
      - 3020:80

  guessir-backend:
    image: dr.k-k.io/guessir-backend
    restart: unless-stopped
    ports:
      - 3030:3020
    environment:
      DB: true
      DB_NAME: guessir
      DB_USER: admin
      DB_PW: password
      DB_HOST: postgres
    links:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guessir
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5435:5432
